services:
  traefik:
    image: "traefik:v3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true" # Correct here
      - "--entrypoints.web.address=:80"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    # labels:
    #   - "traefik.http.routers.api.rule=Host(`instak.cfpt.info`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
    networks:
      - instak.cfpt.info

  api:
    build: ./api
    labels:
      - traefik.enable=true
      - "traefik.http.routers.api.rule=Host(`api.instak.cfpt.info`)"
      - "traefik.http.routers.api.entrypoints=web"
    volumes:
      - ./api/src:/var/www/html
    networks:
      - instak.cfpt.info

  public:
    build: ./public
    volumes:
      - ./public/src:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - "traefik.http.routers.whoami.rule=Host(`instak.cfpt.info`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - instak.cfpt.info

  mongo:
    image: mongo
    restart: "unless-stopped"
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: instacfpt
    networks:
      - instak.cfpt.info

  mongo-express:
    image: mongo-express
    restart: "unless-stopped"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    networks:
      - instak.cfpt.info

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    ports:
      - "9100:9100"
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - instak.cfpt.info

  mongo-exporter:
    image: percona/mongodb_exporter:0.39.0
    restart: unless-stopped
    ports:
      - "9216:9216"
    environment:
      MONGODB_URI: mongodb://admin:admin@mongo:27017
    command:
      - "--collect-all"
      - "--compatible-mode"
    networks:
      - instak.cfpt.info

  prometheus:
    image: prom/prometheus:latest
    restart: "unless-stopped"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - instak.cfpt.info

  grafana:
    image: grafana/grafana:latest
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - instak.cfpt.info

volumes:
  grafana-data:
  mongo-data:


networks:
  instak.cfpt.info:
    driver: bridge
